name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.board }} (${{ matrix.app.conf_name }})
    strategy:
      fail-fast: false
      matrix:
        board:
          - nrf52840dk/nrf52840
          - nrf54l15dk/nrf54l15/cpuapp
        app:
          - path: ../zephyr/samples/bluetooth/hci_usb
            conf_name: default
            cmake_extra_args: ""
          - path: ../zephyr/samples/bluetooth/hci_usb
            conf_name: usbd_next
            cmake_extra_args: "-DCONF_FILE=usbd_next_prj.conf"
          - path: ../zephyr/samples/bluetooth/hci_usb
            conf_name: ACL_502
            cmake_extra_args: "-DEXTRA_CONF_FILE=hci_usb/ACL_502.conf"

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          path: working_directory
          persist-credentials: false

      - uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: working_directory
          toolchains: arm-zephyr-eabi
          ccache-cache-key: ${{ matrix.board }}-${{ matrix.app.conf_name }}-ccache

      - working-directory: working_directory
        run: west build -b ${{ matrix.board }} ${{ matrix.app.path }} -- ${{ matrix.app.cmake_extra_args }}

      - run: |
          zephyr_version=$(west list zephyr --format='{revision}')
          board_slug=$(echo "${{ matrix.board }}" | tr '/' '_')
          app_name=$(basename "${{ matrix.app.path }}")
          fw_name="zephyr_${app_name}_${{ matrix.app.conf_name }}_${zephyr_version}_${board_slug}.hex"
          cp build/zephyr/zephyr.hex "build/${fw_name}"
          echo "name=${fw_name}" >> "$GITHUB_OUTPUT"
        id: fw
        working-directory: working_directory

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.fw.outputs.name }}
          path: working_directory/build/${{ steps.fw.outputs.name }}
          archive: false
